# -*- coding: utf-8 -*-
"""Streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YAW9u4pbA7jzpYinFBBV9qJU8PXqDi9M
"""



# Commented out IPython magic to ensure Python compatibility.
#%%writefile app.py

import streamlit as st

st.set_page_config(page_title="Vineet | ML × Product × Strategy", layout="wide")

st.title("👋 Hi, I'm Vineet")
st.subheader("ML Leader | Business-First Thinker | Product Whisperer")
st.markdown("Helping companies transform ideas into ML-powered impact.")

st.header("About Me")
st.markdown(\"\"\" I'm a Data Scientist with 10 years of experience...\"\"\")

st.header("🚀 Featured Apps")
projects = {
    "Smart Pricing Simulator": "Simulate pricing & discover optimal tiers.",
    "Retention First Aid": "Diagnose churn and act with ML+LLM help.",
    "GenAI Use Case Explorer": "Break out of chatbot thinking!",
}
for title, desc in projects.items():
    st.subheader(title)
    st.write(desc)

st.header("📬 Get in Touch")
st.markdown("Email me at [vineet@example.com](mailto:vineet@example.com)")


